export const ROUTE_NAME = {
  MODAL: "modal",
  SIGN_IN: "sign-in",
  TABS: "(tabs)",
  HOME: "index",
  PROFILE: "profile",
  SIGN_UP: "sign-up",
  FORGOT_PASSWORD: "forgot-password",
  PASSWORD_RESET_SENT: "password-reset-sent",
  RESET_PASSWORD: "reset-password",
  PASSWORD_CHANGED: "password-changed",
  LANDING: "landing",
  ONBOARDING: "onboarding",
  VERIFY_EMAIL: "verify-email",
  EMAIL_VERIFIED: "email-verified",
  COMPLETE_PROFILE: "complete-profile",
  PROFILE_COMPLETED: "profile-completed",
  SETTINGS: "settings",
  EDIT_PROFILE: "edit-profile",
  APP_LANGUAGE: "app-language",
  CONTACT_SUPPORT: "contact-support",
  TERM_OF_USE: "term-of-use",
  PRIVACY_POLICY: "privacy-policy",
  CHANGE_PASSWORD: "change-password",
} as const;

/**
 * type-safe route constants to be used on the app
 */
export const ROUTE = {
  ROOT: "/" as const,
  SIGN_IN: `/${ROUTE_NAME.SIGN_IN}` as const,
  TABS: `/${ROUTE_NAME.TABS}` as const,
  MODAL: `/${ROUTE_NAME.MODAL}` as const,
  HOME: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.HOME}` as const,
  PROFILE: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.PROFILE}` as const,
  SIGN_UP: `/${ROUTE_NAME.SIGN_UP}` as const,
  FORGOT_PASSWORD: `/${ROUTE_NAME.FORGOT_PASSWORD}` as const,
  PASSWORD_RESET_SENT: `/${ROUTE_NAME.PASSWORD_RESET_SENT}` as const,
  RESET_PASSWORD: `/${ROUTE_NAME.RESET_PASSWORD}` as const,
  PASSWORD_CHANGED: `/${ROUTE_NAME.PASSWORD_CHANGED}` as const,
  LANDING: `/${ROUTE_NAME.LANDING}` as const,
  ONBOARDING: `/${ROUTE_NAME.ONBOARDING}` as const,
  VERIFY_EMAIL: `/${ROUTE_NAME.VERIFY_EMAIL}` as const,
  EMAIL_VERIFIED: `/${ROUTE_NAME.EMAIL_VERIFIED}` as const,
  COMPLETE_PROFILE: `/${ROUTE_NAME.COMPLETE_PROFILE}` as const,
  PROFILE_COMPLETED: `/${ROUTE_NAME.PROFILE_COMPLETED}` as const,
  SETTINGS: `/${ROUTE_NAME.SETTINGS}` as const,
  EDIT_PROFILE: `/${ROUTE_NAME.EDIT_PROFILE}` as const,
  APP_LANGUAGE: `/${ROUTE_NAME.APP_LANGUAGE}` as const,
  CONTACT_SUPPORT: `/${ROUTE_NAME.CONTACT_SUPPORT}` as const,
  TERM_OF_USE: `/${ROUTE_NAME.TERM_OF_USE}` as const,
  PRIVACY_POLICY: `/${ROUTE_NAME.PRIVACY_POLICY}` as const,
  CHANGE_PASSWORD: `/${ROUTE_NAME.CHANGE_PASSWORD}` as const,
} as const;
